config/routes.rb
Rails.application.routes.draw do
  get 'menus/index'

  post 'menus/index', to: 'menus#index1'

  get 'menus/lobby'

  get 'procedures/index'

  get 'procedures/new'

  post 'procedures/new', to: 'procedures#new2'

  post 'procedures/edit/:id', to: 'procedures#edit2'

  post 'procedures/delete/:id', to: 'procedures#delete2'

  get 'procedures/edit/:id' => 'procedures#edit', as: 'procedures_edit'

  get 'procedures/show/:id' => 'procedures#show', as: 'procedures_show'

  get 'procedures/delete/:id' => 'procedures#delete', as: 'procedures_delete'

  get 'checks/index'

  get 'checks/new'

  post 'checks/new', to: 'checks#new2'

  post 'checks/edit/:id', to: 'checks#edit2'

  post 'checks/delete/:id', to: 'checks#delete2'

  get 'checks/edit/:id' => 'checks#edit', as: 'checks_edit'

  get 'checks/show/:id' => 'checks#show', as: 'checks_show'

  get 'checks/delete/:id' => 'checks#delete', as: 'checks_delete'

  get 'triggers/index'

  get 'triggers/new'

  post 'triggers/new', to: 'triggers#new2'

  post 'triggers/edit/:id', to: 'triggers#edit2'

  post 'triggers/delete/:id', to: 'triggers#delete2'

  get 'triggers/edit/:id' => 'triggers#edit', as: 'triggers_edit'

  get 'triggers/show/:id' => 'triggers#show', as: 'triggers_show'

  get 'triggers/delete/:id' => 'triggers#delete', as: 'triggers_delete'

  get 'indexes/index'

  get 'indexes/new'

  post 'indexes/new', to: 'indexes#new2'

  post 'indexes/edit/:id', to: 'indexes#edit2'

  post 'indexes/delete/:id', to: 'indexes#delete2'

  get 'indexes/edit/:id' => 'indexes#edit', as: 'indexes_edit'

  get 'indexes/show/:id' => 'indexes#show', as: 'indexes_show'

  get 'indexes/delete/:id' => 'indexess#delete', as: 'indexes_delete'

  get 'views/index'

  get 'views/new'

  post 'views/new', to: 'views#new2'

  post 'views/edit/:id', to: 'views#edit2'

  post 'views/delete/:id', to: 'views#delete2'

  get 'views/edit/:id' => 'views#edit', as: 'views_edit'

  get 'views/show/:id' => 'views#show', as: 'views_show'

  get 'views/delete/:id' => 'views#delete', as: 'views_delete'

  get 'tables/index'

  get 'tables/new'

  post 'tables/new', to: 'tables#new2'

  post 'tables/edit/:id', to: 'tables#edit2'

  post 'tables/delete/:id', to: 'tables#delete2'

  get 'tables/edit/:id' => 'tables#edit', as: 'tables_edit'

  get 'tables/show/:id' => 'tables#show', as: 'tables_show'

  get 'tables/delete/:id' => 'tables#delete', as: 'tables_delete'

  get 'users/index'

  get 'users/new'
  
  post 'users/new', to: 'users#new2'

  post 'users/edit/:id', to: 'users#edit2'

  post 'users/delete/:id', to: 'users#delete2'

  get 'users/edit/:id' => 'users#edit', as: 'users_edit'

  get 'users/show/:id' => 'users#show', as: 'users_show'

  get 'users/delete/:id' => 'users#delete', as: 'users_delete'

  get 'user/show'

  get 'user/new'

  get 'user/edit'

  get 'user/delete'

  get 'user/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  def index
  end

  def new
  end

  def edit
    @oscar = params[:id]
  end

  def show
    @oscar = params[:id]
  end

  def delete
    @oscar = params[:id]
  end

  def new2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def edit2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  #queda pendiente el delete de checks
  def delete2
    @oscar= params[:id]
    @sql1="select relname from pg_class where oid=(select conrelid from pg_constraint where conname ='"+@oscar+"')"
    tablena = ActiveRecord::Base.connection.exec_query(@sql2)
    @sql2 = " ALTER TABLE "+tablena["relname"]+" DROP CONSTRAINT "+@oscar
    ActiveRecord::Base.connection.exec_query(@sql2)
  end
end

app/controllers/indexes_controller.rb
class IndexesController < ApplicationController
  def index
  end

  def new
  end

  def edit
    @oscar = params[:id]
  end

  def show
    @oscar = params[:id]
  end

  def delete
    @oscar = params[:id]
  end

  def new2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def edit2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def delete2
    @oscar= params[:id]
    @sql = "DROP INDEX "+@oscar
    ActiveRecord::Base.connection.exec_query(@sql)
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  def index
  end

  def new
  end

  def edit
    @oscar = params[:id]
  end

  def show
    @oscar = params[:id]
  end

  def delete
    @oscar = params[:id]
  end

  def new2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def edit2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def delete2
    @oscar= params[:id]
    @sql = "DROP FUNCTION "+@oscar
    ActiveRecord::Base.connection.exec_query(@sql)
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
  end

  def new
  end

  def edit
    @oscar = params[:id]
  end

  def show
    @oscar = params[:id]
  end

  def delete
    @oscar = params[:id]
  end

  def new2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def edit2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def delete2
    @oscar= params[:id]
    @sql = "DROP TABLE "+@oscar
    ActiveRecord::Base.connection.exec_query(@sql)
  end
end

app/controllers/triggers_controller.rb
class TriggersController < ApplicationController
  def index
  end

  def new
  end

  def edit
    @oscar = params[:id]
  end

  def show
    @oscar = params[:id]
  end

  def delete
    @oscar = params[:id]
  end

  def new2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def edit2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def delete2
    @oscar= params[:id]
    @sql = "DROP TRIGGER "+@oscar
    ActiveRecord::Base.connection.exec_query(@sql)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def edit
    @oscar = params[:id]
  end

  def show
    @oscar = params[:id]
  end

  def delete
    @oscar = params[:id]
  end

  def new2
    @field1 = params[:usernames]
    @field2 = params[:passwords]
    @sql = "CREATE USER "+@field1+" WITH PASSWORD "+"'"+@field2+"'"
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def edit2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def delete2
    @oscar= params[:id]
    @sql = "DROP USER "+@oscar
    ActiveRecord::Base.connection.exec_query(@sql)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  def index
  end

  def new
  end

  def edit
    @oscar = params[:id]
  end

  def show
    @oscar = params[:id]
  end

  def delete
    @oscar = params[:id]
  end

  def new2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def edit2
    @sql= params[:sqls]
    ActiveRecord::Base.connection.exec_query(@sql)
  end

  def delete2
    @oscar= params[:id]
    @sql = "DROP VIEW "+@oscar
    ActiveRecord::Base.connection.exec_query(@sql)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/indexes_helper.rb
module IndexesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/triggers_helper.rb
module TriggersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/checks/delete.html.erb
<h1>ARE YOU SURE YOU WANT TO DELETE...:</h1>
<h2>CHECK: <%=@oscar%></h2>
<hr>
<%sqq = "select * from pg_constraint where conname='"+@oscar+"'"%>
<%sqs = "select pg_get_constraintdef(oid) from pg_constraint where conname='"+@oscar+"'"%>
<% rows = ActiveRecord::Base.connection.exec_query(sqq)%>
<%rows.each do |row|%>
    <h2><%=row["conname"] %></h2>
<%end%>
<% rows = ActiveRecord::Base.connection.exec_query(sqs)%>
<%rows.each do |row|%>
    <h2><%=row["pg_get_constraintdef"] %></h2>
<%end%>
<%= submit_tag 'Delete' %>
<hr>
<h2><%= link_to "Back", checks_index_path %></h2>

app/views/checks/edit.html.erb
<h1>CHECK CONSTRAINT:</h1>
<p>Edit:</p>
<p><%=@oscar%></p>
<hr>
<%sqs = "select pg_get_constraintdef(oid) from pg_constraint where conname='"+@oscar+"'"%>
<% rows = ActiveRecord::Base.connection.exec_query(sqs)%>
<% vivi = "Hallo"%>
<%rows.each do |row|%>
    <% vivi = row["pg_get_constraintdef"] %>
<%end%>
<%= form_tag do %>
    EXECUTE SQL: <%= text_area_tag :sqls, nil, size: "85x25", placeholder: vivi%><br />
    <%= submit_tag 'Edit' %>
    <%end%>
<hr>
<h2><%= link_to "Back", checks_index_path %></h2>

app/views/checks/index.html.erb
<h1>CHECKS CONSTRAINS</h1>
<p>By User:</p>
<h2><%= link_to "Lobby", menus_lobby_path %></h2>
<hr>
<% rows = ActiveRecord::Base.connection.exec_query('SELECT conname FROM pg_constraint')%>
<%rows.each do |row|%>
    <h2><%=@oscar = row["conname"] %></h2>
    <%= link_to "Show", checks_show_path(@oscar) %>
    <%= link_to "Edit", checks_edit_path(@oscar) %>
    <%= link_to "Delete", checks_delete_path(@oscar) %>
<%end%>
<hr>
<h2><%= link_to "New", checks_new_path %></h2>

app/views/checks/new.html.erb
<h1>CHECK</h1>
<p>New:</p>
<hr>
<%= form_tag do %>
EXECUTE SQL: <%= text_area_tag :sqls, nil, size: "85x25"%><br />
<%= submit_tag 'Create' %>
<%end%>
<hr>
<h2><%= link_to "Back", checks_index_path %></h2>

app/views/checks/show.html.erb
<h1>CHECK:</h1>
<hr>
<%sqq = "select * from pg_constraint where conname='"+@oscar+"'"%>
<%sqs = "select pg_get_constraintdef(oid) from pg_constraint where conname='"+@oscar+"'"%>
<% rows = ActiveRecord::Base.connection.exec_query(sqq)%>
<%rows.each do |row|%>
    <h2><%=row["conname"] %></h2>
<%end%>
<% rows = ActiveRecord::Base.connection.exec_query(sqs)%>
<%rows.each do |row|%>
    <h2><%=row["pg_get_constraintdef"] %></h2>
<%end%>
<hr>
<h2><%= link_to "Back", checks_index_path %></h2>